spring.datasource.url=jdbc:mysql://localhost:3306/ezcerts?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
# Ajusta la contraseña si tu instancia local de MySQL tiene una.

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

spring.thymeleaf.cache=false
